# This file sets "stakes" for the various tests
#
# A stake is just a marker. An ideal value for a specific test, usina set
# build on a a specific machine at a specific time.
#
# Stakes are used to compare new runs against. Stakes can and should be
# updated when there is a reason to.
#
# Each stake has a value, a date and an optional description
#
# The stakes are set per test. Each test is identified by its unique name.
# That name is disaplayed within parenteses in the test section subtitles.
#
[100G-speed]
  val: 5475738172
  date: 2026-08-11
  desc: initial

[single-numallocs]
  val: 100
  date: 2026-08-12
  desc: DNS + dedotdot cleanups

[single-maxalloc]
  val: 130622
  date: 2026-08-12
  desc: after #22547

[h1parallel-speed]
  val: 3518118326
  date: 2026-08-11
  desc: initial

[h2parallel-speed]
  val: 2604657540
  date: 2026-08-11
  desc: initial

[h3parallel-speed]
  val: 1098816436
  date: 2026-08-11
  desc: initial

[h1parallel-mem]
  val: 21989653
  date: 2026-08-11
  desc: initial

[h2parallel-mem]
  val: 14281647
  date: 2026-08-11
  desc: initial

[h3parallel-mem]
  val: 15606417
  date: 2026-08-11
  desc: initial

[h1parallel-upload-speed]
  val: 2475714830
  date: 2026-08-11
  desc: initial

[h2parallel-upload-speed]
  val: 1649047518
  date: 2026-08-11
  desc: initial

[h3parallel-upload-speed]
  val: 322526712
  date: 2026-08-11
  desc: adjusted

[h1parallel-upload-mem]
  val: 22748540
  date: 2026-08-11
  desc: initial

[h2parallel-upload-mem]
  val: 21196967
  date: 2026-08-11
  desc: initial

[h3parallel-upload-mem]
  val: 543180800
  date: 2026-08-12
  desc: rss-max

[h1-requests]
  val: 31096
  date: 2026-08-11
  desc: early

[h2-requests]
  val: 30399
  date: 2026-08-11
  desc: early

[h3-requests]
  val: 28920
  date: 2026-08-11
  desc: early

[h1-req-mem]
  val: 18300928
  date: 2026-08-11
  desc: maybe

[h2-req-mem]
  val: 13266776
  date: 2026-08-11
  desc: maybe

[h3-req-mem]
  val: 13835665
  date: 2026-08-11
  desc: maybe

[easy-handle]
  val: 4256
  date: 2026-08-12
  desc: initial

[multi-handle]
  val: 880
  date: 2026-08-12
  desc: initial

[connectdata]
  val: 823
  date: 2026-08-12
  desc: initial
