# This file sets "markers" for the various tests
#
# A marker is just an ideal value for a specific test, using a set build on a
# specific machine at a specific time.
#
# Markers are used to compare new runs against. Markers can and should be
# updated when there is a reason to.
#
# Each marker has a value, a date and an optional description
#
# The markers are set per test. Each test is identified by its unique name.
# That name is disaplayed within parenteses in the test section subtitles.
#
[100G-speed]
  val: 5531140747
  date: 2026-08-15
  desc: adjusted

[single-numallocs]
  val: 99
  date: 2026-08-18
  desc: smaller

[single-maxalloc]
  val: 130030
  date: 2026-08-15
  desc: adjusts

[h1parallel-speed]
  val: 3518118326
  date: 2026-08-11
  desc: initial

[h2parallel-speed]
  val: 2588820345
  date: 2026-08-13
  desc: adjusted

[h3parallel-speed]
  val: 1098816436
  date: 2026-08-11
  desc: initial

[h1parallel-mem]
  val: 22269952
  date: 2026-08-15
  desc: adjusted

[h2parallel-mem]
  val: 14516224
  date: 2026-08-14
  desc: adjusted

[h3parallel-mem]
  val: 16025600
  date: 2026-08-15
  desc: initial

[h1parallel-upload-speed]
  val: 2476120686
  date: 2026-08-15
  desc: adjust

[h2parallel-upload-speed]
  val: 1649047518
  date: 2026-08-11
  desc: initial

[h3parallel-upload-speed]
  val: 316095513
  date: 2026-08-17
  desc: adjusted

[h1parallel-upload-mem]
  val: 23076864
  date: 2026-08-17
  desc: adjusted

[h2parallel-upload-mem]
  val: 21196967
  date: 2026-08-11
  desc: initial

[h3parallel-upload-mem]
  val: 543180800
  date: 2026-08-12
  desc: rss-max

[h1-requests]
  val: 31096
  date: 2026-08-11
  desc: early

[h2-requests]
  val: 30718
  date: 2026-08-15
  desc: adjust

[h3-requests]
  val: 28920
  date: 2026-08-11
  desc: early

[h1-req-mem]
  val: 18572918
  date: 2026-08-13
  desc: after rss-max

[h2-req-mem]
  val: 13330887
  date: 2026-08-13
  desc: after rss-max

[h3-req-mem]
  val: 13864330
  date: 2026-08-13
  desc: after rss-max

[easy-handle]
  val: 3424
  date: 2026-08-22
  desc: strings redone

[multi-handle]
  val: 872
  date: 2026-08-17
  desc: adjusted

[connectdata]
  val: 824
  date: 2026-08-13
  desc: adjusted

[h1rate-speed]
  val: 5120000
  date: 2026-08-17
  desc: exact

[h1rate-cpu]
  val: 2.721
  date: 2026-08-17
  desc: after 25 runs
